import { INodeProperties } from 'n8n-workflow';

export const brandAutomationOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['brandAutomation'] } },
		options: [
			{ name: 'Disable', value: 'disable', description: 'Disable automation for a brand', action: 'Disable brand automation' },
			{ name: 'Enable', value: 'enable', description: 'Enable automation for a brand', action: 'Enable brand automation' },
			{ name: 'Extend Queue', value: 'extendQueue', description: 'Extend automation queue', action: 'Extend automation queue' },
			{ name: 'Get Resolved Prompt', value: 'getResolvedPrompt', description: 'Get system prompt with variables replaced', action: 'Get resolved prompt' },
			{ name: 'Get Stats', value: 'getStats', description: 'Get automation statistics', action: 'Get automation stats' },
			{ name: 'Get System Prompts', value: 'getSystemPrompts', description: 'Get text and image system prompts', action: 'Get system prompts' },
			{ name: 'Trigger', value: 'trigger', description: 'Trigger automation processing', action: 'Trigger automation' },
			{ name: 'Update Settings', value: 'updateSettings', description: 'Update automation settings', action: 'Update automation settings' },
			{ name: 'Update System Prompts', value: 'updateSystemPrompts', description: 'Update text or image system prompts', action: 'Update system prompts' },
		],
		default: 'getStats',
	},
];

export const brandAutomationFields: INodeProperties[] = [
	{
		displayName: 'Brand Name or ID',
		name: 'brandId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getBrands' },
		required: true,
		default: '',
		description: 'The brand to use. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['brandAutomation'] } },
	},
	// ----------------------------------
	//   extendQueue
	// ----------------------------------
	{
		displayName: 'Count',
		name: 'count',
		type: 'number',
		default: 5,
		description: 'Number of posts to add to the queue',
		displayOptions: { show: { resource: ['brandAutomation'], operation: ['extendQueue'] } },
	},
	// ----------------------------------
	//   updateSettings
	// ----------------------------------
	{
		displayName: 'Settings',
		name: 'settings',
		type: 'collection',
		placeholder: 'Add Setting',
		default: {},
		displayOptions: { show: { resource: ['brandAutomation'], operation: ['updateSettings'] } },
		options: [
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'options',
				options: [
					{ name: 'Daily', value: 'daily' },
					{ name: 'Every 2 Days', value: 'every_2_days' },
					{ name: 'Every 3 Days', value: 'every_3_days' },
					{ name: 'Weekly', value: 'weekly' },
					{ name: 'Twice a Week', value: 'twice_weekly' },
					{ name: '3 Times a Week', value: 'three_weekly' },
					{ name: 'Custom', value: 'custom' },
				],
				default: 'daily',
				description: 'Posting frequency',
			},
			{
				displayName: 'Posts Per Day',
				name: 'posts_per_day',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1, maxValue: 10 },
				description: 'Number of posts per day (when frequency allows)',
			},
			{
				displayName: 'Platforms',
				name: 'platforms',
				type: 'multiOptions',
				options: [
					{ name: 'Facebook', value: 'facebook' },
					{ name: 'Instagram', value: 'instagram' },
					{ name: 'Twitter/X', value: 'twitter' },
					{ name: 'LinkedIn', value: 'linkedin' },
					{ name: 'TikTok', value: 'tiktok' },
					{ name: 'YouTube', value: 'youtube' },
					{ name: 'Pinterest', value: 'pinterest' },
					{ name: 'Threads', value: 'threads' },
				],
				default: [],
				description: 'Target platforms for automated posts',
			},
			{ displayName: 'Auto Approve', name: 'auto_approve', type: 'boolean', default: false, description: 'Whether to auto-approve generated posts' },
			{ displayName: 'Auto Publish', name: 'auto_publish', type: 'boolean', default: false, description: 'Whether to auto-publish approved posts' },
			{
				displayName: 'Default Language',
				name: 'language',
				type: 'options',
				options: [
					{ name: 'Afrikaans', value: 'af' },
					{ name: 'Albanian', value: 'sq' },
					{ name: 'Amharic', value: 'am' },
					{ name: 'Arabic', value: 'ar' },
					{ name: 'Armenian', value: 'hy' },
					{ name: 'Azerbaijani', value: 'az' },
					{ name: 'Basque', value: 'eu' },
					{ name: 'Belarusian', value: 'be' },
					{ name: 'Bengali', value: 'bn' },
					{ name: 'Bosnian', value: 'bs' },
					{ name: 'Bulgarian', value: 'bg' },
					{ name: 'Catalan', value: 'ca' },
					{ name: 'Chinese (Simplified)', value: 'zh-CN' },
					{ name: 'Chinese (Traditional)', value: 'zh-TW' },
					{ name: 'Croatian', value: 'hr' },
					{ name: 'Czech', value: 'cs' },
					{ name: 'Danish', value: 'da' },
					{ name: 'Dutch', value: 'nl' },
					{ name: 'English', value: 'en' },
					{ name: 'English (UK)', value: 'en-GB' },
					{ name: 'English (US)', value: 'en-US' },
					{ name: 'Estonian', value: 'et' },
					{ name: 'Filipino', value: 'fil' },
					{ name: 'Finnish', value: 'fi' },
					{ name: 'French', value: 'fr' },
					{ name: 'French (Canada)', value: 'fr-CA' },
					{ name: 'Galician', value: 'gl' },
					{ name: 'Georgian', value: 'ka' },
					{ name: 'German', value: 'de' },
					{ name: 'German (Austria)', value: 'de-AT' },
					{ name: 'German (Switzerland)', value: 'de-CH' },
					{ name: 'Greek', value: 'el' },
					{ name: 'Gujarati', value: 'gu' },
					{ name: 'Hebrew', value: 'he' },
					{ name: 'Hindi', value: 'hi' },
					{ name: 'Hungarian', value: 'hu' },
					{ name: 'Icelandic', value: 'is' },
					{ name: 'Indonesian', value: 'id' },
					{ name: 'Irish', value: 'ga' },
					{ name: 'Italian', value: 'it' },
					{ name: 'Japanese', value: 'ja' },
					{ name: 'Kannada', value: 'kn' },
					{ name: 'Kazakh', value: 'kk' },
					{ name: 'Khmer', value: 'km' },
					{ name: 'Korean', value: 'ko' },
					{ name: 'Kurdish', value: 'ku' },
					{ name: 'Kyrgyz', value: 'ky' },
					{ name: 'Lao', value: 'lo' },
					{ name: 'Latvian', value: 'lv' },
					{ name: 'Lithuanian', value: 'lt' },
					{ name: 'Macedonian', value: 'mk' },
					{ name: 'Malay', value: 'ms' },
					{ name: 'Malayalam', value: 'ml' },
					{ name: 'Maltese', value: 'mt' },
					{ name: 'Marathi', value: 'mr' },
					{ name: 'Mongolian', value: 'mn' },
					{ name: 'Nepali', value: 'ne' },
					{ name: 'Norwegian', value: 'no' },
					{ name: 'Pashto', value: 'ps' },
					{ name: 'Persian (Farsi)', value: 'fa' },
					{ name: 'Polish', value: 'pl' },
					{ name: 'Portuguese (Brazil)', value: 'pt-BR' },
					{ name: 'Portuguese (Portugal)', value: 'pt' },
					{ name: 'Punjabi', value: 'pa' },
					{ name: 'Romanian', value: 'ro' },
					{ name: 'Russian', value: 'ru' },
					{ name: 'Serbian', value: 'sr' },
					{ name: 'Sinhala', value: 'si' },
					{ name: 'Slovak', value: 'sk' },
					{ name: 'Slovenian', value: 'sl' },
					{ name: 'Somali', value: 'so' },
					{ name: 'Spanish', value: 'es' },
					{ name: 'Spanish (Latin America)', value: 'es-419' },
					{ name: 'Spanish (Mexico)', value: 'es-MX' },
					{ name: 'Swahili', value: 'sw' },
					{ name: 'Swedish', value: 'sv' },
					{ name: 'Tamil', value: 'ta' },
					{ name: 'Telugu', value: 'te' },
					{ name: 'Thai', value: 'th' },
					{ name: 'Turkish', value: 'tr' },
					{ name: 'Ukrainian', value: 'uk' },
					{ name: 'Urdu', value: 'ur' },
					{ name: 'Uzbek', value: 'uz' },
					{ name: 'Vietnamese', value: 'vi' },
					{ name: 'Welsh', value: 'cy' },
					{ name: 'Zulu', value: 'zu' },
				],
				default: 'pl',
				description: 'Default language for generated content',
			},
			{
				displayName: 'Default Tone',
				name: 'tone',
				type: 'options',
				options: [
					{ name: 'Professional', value: 'professional' },
					{ name: 'Casual', value: 'casual' },
					{ name: 'Friendly', value: 'friendly' },
					{ name: 'Formal', value: 'formal' },
					{ name: 'Humorous', value: 'humorous' },
					{ name: 'Inspirational', value: 'inspirational' },
				],
				default: 'professional',
				description: 'Default tone for generated content',
			},
		],
	},
	// ----------------------------------
	//   getResolvedPrompt
	// ----------------------------------
	{
		displayName: 'Prompt Type',
		name: 'promptType',
		type: 'options',
		options: [
			{ name: 'Text', value: 'text', description: 'Text generation system prompt' },
			{ name: 'Image', value: 'image', description: 'Image generation system prompt' },
		],
		default: 'text',
		required: true,
		description: 'The type of system prompt to get',
		displayOptions: { show: { resource: ['brandAutomation'], operation: ['getResolvedPrompt'] } },
	},
	// ----------------------------------
	//   updateSystemPrompts
	// ----------------------------------
	{
		displayName: 'Prompts',
		name: 'prompts',
		type: 'collection',
		placeholder: 'Add Prompt',
		default: {},
		displayOptions: { show: { resource: ['brandAutomation'], operation: ['updateSystemPrompts'] } },
		options: [
			{
				displayName: 'Text System Prompt',
				name: 'text_system_prompt',
				type: 'string',
				typeOptions: { rows: 6 },
				default: '',
				description: 'System prompt for text generation. Use variables like {{brand_name}}, {{industry}}, {{pain_points}}, etc.',
			},
			{
				displayName: 'Image System Prompt',
				name: 'image_system_prompt',
				type: 'string',
				typeOptions: { rows: 6 },
				default: '',
				description: 'System prompt for image generation. Use variables like {{brand_name}}, {{industry}}, {{tone}}, etc.',
			},
		],
	},
];
