import { INodeProperties } from 'n8n-workflow';

export const rowOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['row'] } },
		options: [
			{ name: 'Bulk Create', value: 'bulkCreate', description: 'Create multiple rows', action: 'Bulk create rows' },
			{ name: 'Bulk Delete', value: 'bulkDelete', description: 'Delete multiple rows', action: 'Bulk delete rows' },
			{ name: 'Create', value: 'create', description: 'Create a row', action: 'Create a row' },
			{ name: 'Delete', value: 'delete', description: 'Delete a row', action: 'Delete a row' },
			{ name: 'Get', value: 'get', description: 'Get a row', action: 'Get a row' },
			{ name: 'Get Many', value: 'getAll', description: 'Get many rows', action: 'Get many rows' },
			{ name: 'Reorder', value: 'reorder', description: 'Reorder a row', action: 'Reorder a row' },
			{ name: 'Update', value: 'update', description: 'Update a row', action: 'Update a row' },
			{ name: 'Upsert', value: 'upsert', description: 'Create a new row or update an existing one based on a matching field', action: 'Upsert a row' },
		],
		default: 'getAll',
	},
];

export const rowFields: INodeProperties[] = [
	// Helper baseId for tableId dropdown
	{
		displayName: 'Base Name or ID',
		name: 'baseId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getBases' },
		required: true,
		default: '',
		description: 'Select the base first to populate the table dropdown. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['row'], operation: ['getAll', 'get', 'create', 'update', 'upsert', 'bulkCreate', 'bulkDelete'] } },
	},
	{
		displayName: 'Table Name or ID',
		name: 'tableId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTables', loadOptionsDependsOn: ['baseId'] },
		required: true,
		default: '',
		description: 'The table to use. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['row'], operation: ['getAll', 'get', 'create', 'update', 'upsert', 'bulkCreate', 'bulkDelete'] } },
	},
	{
		displayName: 'Row ID',
		name: 'rowId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the row',
		displayOptions: { show: { resource: ['row'], operation: ['delete', 'update', 'reorder'] } },
	},
	{
		displayName: 'Search Field Name or ID',
		name: 'searchFieldId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getFields', loadOptionsDependsOn: ['tableId'] },
		required: true,
		default: '',
		description: 'The field to search by. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['row'], operation: ['get'] } },
	},
	{
		displayName: 'Search Value',
		name: 'searchValue',
		type: 'string',
		required: true,
		default: '',
		description: 'The value to look for in the search field',
		displayOptions: { show: { resource: ['row'], operation: ['get'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['row'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['row'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Field Values',
		name: 'fieldValues',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		required: true,
		default: {},
		description: 'The field values to set on the row',
		displayOptions: { show: { resource: ['row'], operation: ['create'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Field Name or ID',
						name: 'fieldId',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getFields', loadOptionsDependsOn: ['tableId'] },
						default: '',
						description: 'The field to set. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
					},
					{
						displayName: 'Value',
						name: 'fieldValue',
						type: 'string',
						default: '',
						description: 'The value to set for this field',
					},
				],
			},
		],
	},
	{
		displayName: 'Field Values',
		name: 'fieldValues',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		required: true,
		default: {},
		description: 'The field values to update on the row',
		displayOptions: { show: { resource: ['row'], operation: ['update'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Field Name or ID',
						name: 'fieldId',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getFields', loadOptionsDependsOn: ['tableId'] },
						default: '',
						description: 'The field to update. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
					},
					{
						displayName: 'Value',
						name: 'fieldValue',
						type: 'string',
						default: '',
						description: 'The new value for this field',
					},
				],
			},
		],
	},
	{
		displayName: 'Match Field Name or ID',
		name: 'matchFieldId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getFields', loadOptionsDependsOn: ['tableId'] },
		required: true,
		default: '',
		description: 'The field to check for existing rows. If a row with the same value in this field exists, it will be updated; otherwise a new row will be created. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['row'], operation: ['upsert'] } },
	},
	{
		displayName: 'Match Value',
		name: 'matchValue',
		type: 'string',
		required: true,
		default: '',
		description: 'The value to look for in the match field',
		displayOptions: { show: { resource: ['row'], operation: ['upsert'] } },
	},
	{
		displayName: 'Field Values',
		name: 'fieldValues',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		required: true,
		default: {},
		description: 'The field values to set on the created or updated row',
		displayOptions: { show: { resource: ['row'], operation: ['upsert'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Field Name or ID',
						name: 'fieldId',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getFields', loadOptionsDependsOn: ['tableId'] },
						default: '',
						description: 'The field to set. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
					},
					{
						displayName: 'Value',
						name: 'fieldValue',
						type: 'string',
						default: '',
						description: 'The value to set for this field',
					},
				],
			},
		],
	},
	{
		displayName: 'Rows',
		name: 'rows',
		type: 'json',
		required: true,
		default: '[]',
		description: 'JSON array of row objects, each containing values (e.g. [{"values": {"field_id": "value"}}])',
		displayOptions: { show: { resource: ['row'], operation: ['bulkCreate'] } },
	},
	{
		displayName: 'Row IDs',
		name: 'rowIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of row IDs to delete',
		displayOptions: { show: { resource: ['row'], operation: ['bulkDelete'] } },
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'number',
		required: true,
		default: 0,
		description: 'New position for the row',
		displayOptions: { show: { resource: ['row'], operation: ['reorder'] } },
	},
];
