import { INodeProperties } from 'n8n-workflow';

export const rowOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['row'] } },
		options: [
			{ name: 'Bulk Create', value: 'bulkCreate', description: 'Create multiple rows', action: 'Bulk create rows' },
			{ name: 'Bulk Delete', value: 'bulkDelete', description: 'Delete multiple rows', action: 'Bulk delete rows' },
			{ name: 'Create', value: 'create', description: 'Create a row', action: 'Create a row' },
			{ name: 'Delete', value: 'delete', description: 'Delete a row', action: 'Delete a row' },
			{ name: 'Get', value: 'get', description: 'Get a row', action: 'Get a row' },
			{ name: 'Get Many', value: 'getAll', description: 'Get many rows', action: 'Get many rows' },
			{ name: 'Reorder', value: 'reorder', description: 'Reorder a row', action: 'Reorder a row' },
			{ name: 'Update', value: 'update', description: 'Update a row', action: 'Update a row' },
		],
		default: 'getAll',
	},
];

export const rowFields: INodeProperties[] = [
	// Helper baseId for tableId dropdown
	{
		displayName: 'Base Name or ID',
		name: 'baseId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getBases' },
		required: true,
		default: '',
		description: 'Select the base first to populate the table dropdown. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['row'], operation: ['getAll', 'create', 'bulkCreate', 'bulkDelete'] } },
	},
	{
		displayName: 'Table Name or ID',
		name: 'tableId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTables', loadOptionsDependsOn: ['baseId'] },
		required: true,
		default: '',
		description: 'The table to use. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['row'], operation: ['getAll', 'create', 'bulkCreate', 'bulkDelete'] } },
	},
	{
		displayName: 'Row ID',
		name: 'rowId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the row',
		displayOptions: { show: { resource: ['row'], operation: ['get', 'delete', 'update', 'reorder'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['row'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['row'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Cells',
		name: 'cells',
		type: 'json',
		required: true,
		default: '{}',
		description: 'JSON object mapping field IDs to values (e.g. {"field_id": "value"})',
		displayOptions: { show: { resource: ['row'], operation: ['create'] } },
	},
	{
		displayName: 'Update Fields',
		name: 'cells',
		type: 'json',
		required: true,
		default: '{}',
		description: 'JSON object mapping field IDs to new values',
		displayOptions: { show: { resource: ['row'], operation: ['update'] } },
	},
	{
		displayName: 'Rows',
		name: 'rows',
		type: 'json',
		required: true,
		default: '[]',
		description: 'JSON array of row objects, each containing cells',
		displayOptions: { show: { resource: ['row'], operation: ['bulkCreate'] } },
	},
	{
		displayName: 'Row IDs',
		name: 'rowIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of row IDs to delete',
		displayOptions: { show: { resource: ['row'], operation: ['bulkDelete'] } },
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'number',
		required: true,
		default: 0,
		description: 'New position for the row',
		displayOptions: { show: { resource: ['row'], operation: ['reorder'] } },
	},
];
